version: '3.4'

x-environment: &env
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: db

services:
    server:
        container_name: api
        build: .
        command: python app.py
        ports:
            - "0.0.0.0:80:80"
        environment: *env
        volumes:
            - ".:/code/"
        depends_on:
            - database
    database:
        container_name: postgres
        image: postgres:13.1
        environment: *env

